development:
  adapter: postgresql
  encoding: unicode
  database: hackcor
  pool: 5
  username: MacriniciDan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hackcor
  pool: 5
  username: MacriniciDan
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: hackcor
  pool: 5
  username:
  password:
