development:
  adapter: postgresql
  encoding: unicode
  database: hackcor
  pool: 5
  username: andreicap
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: hackcor
  pool: 5
  username: andreicap
  password: 