# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d166597aca828cf8aa706006083c3a5d8b6ac01c96ae35f21c9355213d740833b90460cf7707df235a2244dd6ccde82ab0b4ebdde037f3ba13f540cb38612b

test:
  secret_key_base: ce458880e233b392d57a6f7f55e79fd0af72df6f49ff55aec68ed0e421f58a95370137fa05836725adf90c7e35ee33410b0d5c14a2882fe8296fb2a3cc1c44a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV['SECRET_KEY_BASE']
